\"
.\" Copyright (c) 2013 Bertrand Janin <b@janin.com>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd 2013-12-13
.Dt uncsv 1 URM
.Os
.Sh NAME
.Nm uncsv
.Nd convert to or from a CSV stream
.Sh SYNOPSIS
.Nm uncsv
.Bk -words
.Op Fl hV
.Op Fl d Ar delimiter
.Op Fl n Ar repl
.Op Fl r Ar repl
.Op Ar file ...
.Nm csv
.Ek
.Bk -words
.Op Fl hV
.Op Fl d Ar delimiter
.Op Fl n Ar repl
.Op Fl r Ar repl
.Op Ar file ...
.Ek
.Sh DESCRIPTION
.Nm
is a filter command converting the lines of a CSV file into non-escaped,
non-quoted delimited file (pipe by default). This program will error out if it
encounters a character matching the delimiter, it will also replace the
carriage return and new-line characters found in quoted values allowing you
to use awk to play with your CSVs.
.Pp
.Nm csv
is the opposite of this command. It takes an unquoted stream of values, separated
by the delimiter of your choice (default: pipe '|') and produces a "standard" CSV
file.
.Pp
Both tools avoid end-of-line character politics and will leave these untouched,
if your file comes with both carriage returns and new-line characters (\\r\\n
a.k.a. CRLF), uncsv will leave them as-is.
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Fl d Ar delimiter
Specify the output delimiter for
.Nm uncsv
and the input delimiter for
.Nm csv
, defaults to the pipe character '|'.
.Nm uncsv
interrupts if the delimiter is found in the input data.
.It Fl n Ar repl
If specified, all the new-line characters (a.k.a. line feed or \\n) will be
replaced by this replacement string.
.Nm uncsv
replaces them by spaces by default which is destructive.
.Nm csv
will do the opposite and replace this pattern by an actual new line character.
.It Fl r Ar repl
If specified, all the carriage return characters (a.k.a. \\r) will be
replaced by this replacement string.
.Nm uncsv
replaces them by spaces by default which is destructive.
.Nm csv
will do the opposite and replace this pattern by an actual carriage return
character.
.It Fl s
Quote all fields with a heading or trailing space (or tab). This is only
applicable when generating the CSV stream.
.It Fl V
Print version.
.It Fl h
Print usage.
.El
.Sh EXAMPLES
.Pp
 # Print the second field of a CSV:
 uncsv file.csv | cut -d'|' -f 2
.Pp
 # Convert a CSV to un-quoted tab-delimited format:
 uncsv -d'\\t' < file.csv > delimited
.Pp
 # Convert a PostgreSQL output to CSV:
 psql yourdb
 psql> \\f\\a
 psql> \\o | csv > /tmp/output.csv
 psql> select * from candies;
 psql> \\o
.Pp
 # Print the first line of the third field.
 uncsv -n '~LF~' file.csv | cut -d'|' -f 3 | sed 's/~LF~.*//g'
.Pp
 # Convert your /etc/passwd to CSV.
 csv -d: < /etc/passwd
.Sh BUGS
.Nm csv
has a 64KB limit on line size.
.Sh SEE ALSO
.Xr awk 1 ,
.Xr cut 1
.Sh AUTHORS
.Nm
was written by Bertrand Janin <b@janin.com> and is distributed under
an ISC license (BSD compatible, OSI compatible).
