BINARY=uncsv
OBJECTS=main.o
OBJECTS+=${EXTRA_OBJECTS}
HEADERS=

all: ${BINARY}

${BINARY}: ${OBJECTS}
	${CC} ${LDFLAGS} -o ${BINARY} ${OBJECTS}

${OBJECTS}: ${HEADERS}

ctags:
	ctags *.c *.h

clean:
	rm -f ${BINARY} ${OBJECTS}
